--
-- PostgreSQL database dump
--

-- Dumped from database version 12.6 (Ubuntu 12.6-0ubuntu0.20.04.1)
-- Dumped by pg_dump version 12.6 (Ubuntu 12.6-0ubuntu0.20.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: postgis; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS postgis WITH SCHEMA public;


--
-- Name: EXTENSION postgis; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION postgis IS 'PostGIS geometry, geography, and raster spatial types and functions';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: ads; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ads (
    "AdsId" integer NOT NULL,
    "Description" text NOT NULL,
    "ShopId" integer NOT NULL,
    "StartDate" timestamp without time zone NOT NULL,
    "EndDate" timestamp without time zone NOT NULL,
    "IsActive" boolean NOT NULL
);


ALTER TABLE public.ads OWNER TO postgres;

--
-- Name: ads_AdsId_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ads ALTER COLUMN "AdsId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."ads_AdsId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: category; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.category (
    "CategoryId" integer NOT NULL,
    "CategoryName" character varying(200) NOT NULL
);


ALTER TABLE public.category OWNER TO postgres;

--
-- Name: category_CategoryId_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.category ALTER COLUMN "CategoryId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."category_CategoryId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: location; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.location (
    "LocationId" integer NOT NULL,
    "LocationName" character varying(500),
    "GeoLoacation" public.geometry NOT NULL
);


ALTER TABLE public.location OWNER TO postgres;

--
-- Name: location_LocationId_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.location ALTER COLUMN "LocationId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."location_LocationId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notifications; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.notifications (
    "NotificatoinId" integer NOT NULL ,
    "UserId" integer NOT NULL,
    "NotificationMessage" character varying(500),
    "NotificationType" text,
    "Seen" boolean NOT NULL
);


ALTER TABLE public.notifications OWNER TO postgres;

--
-- Name: notifications_NotificatoinId_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.notifications ALTER COLUMN "NotificatoinId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."notifications_NotificatoinId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: products; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.products (
    "ProductId" integer NOT NULL,
    "ShopId" integer NOT NULL,
    "ProductName" text NOT NULL,
    "DateInserted" timestamp without time zone NOT NULL,
    "Brand" text,
    "Description" text,
    "CategoryId" integer NOT NULL,
    "Price" integer NOT NULL,
    "Condition" text,
    "ImageUrl" text,
    "DeliveryAvailable" boolean NOT NULL,
    "Discount" integer NOT NULL,
    "ProductCount" integer NOT NULL,
    "ProductReviewId" integer
);


ALTER TABLE public.products OWNER TO postgres;

--
-- Name: products_ProductId_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.products ALTER COLUMN "ProductId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."products_ProductId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reviews; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.reviews (
    "UserId" integer NOT NULL,
    "ProductId" integer NOT NULL,
    "ReviewId" integer NOT NULL,
    "Rating" integer NOT NULL,
    "Comment" character varying(500) NOT NULL,
    "ReviewDate" timestamp without time zone NOT NULL
);


ALTER TABLE public.reviews OWNER TO postgres;

--
-- Name: reviews_ReviewId_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.reviews ALTER COLUMN "ReviewId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."reviews_ReviewId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: shopFollow; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."shopFollow" (
    "ShopLikeId" integer NOT NULL,
    "UserId" integer NOT NULL,
    "ShopId" integer NOT NULL
);


ALTER TABLE public."shopFollow" OWNER TO postgres;

--
-- Name: shopFollow_ShopLikeId_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."shopFollow" ALTER COLUMN "ShopLikeId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."shopFollow_ShopLikeId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: shops; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.shops (
    "ShopId" integer NOT NULL,
    "ShopName" text NOT NULL,
    "BuildingName" character varying(150),
    "PhoneNumber" character varying(50) NOT NULL,
    "CoverImage" text,
    "OwnerId" integer NOT NULL,
    "CategoryId" integer NOT NULL,
    "ShopLocationId" integer NOT NULL,
    "Description" character varying(500),
    "IsActive" boolean
);


ALTER TABLE public.shops OWNER TO postgres;

--
-- Name: shops_ShopId_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.shops ALTER COLUMN "ShopId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."shops_ShopId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    "UserId" integer NOT NULL,
    "Username" character varying(60) NOT NULL,
    "Email" text NOT NULL,
    "Password" text NOT NULL,
    "Role" text NOT NULL,
    "Phone" text,
    "DateAccountCreated" timestamp without time zone NOT NULL
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Name: users_UserId_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN "UserId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."users_UserId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: wishList; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."wishList" (
    "WishListItemId" integer NOT NULL,
    "ProductId" integer NOT NULL,
    "UserId" integer NOT NULL,
    "DateAdded" timestamp without time zone NOT NULL
);


ALTER TABLE public."wishList" OWNER TO postgres;

--
-- Name: wishList_WishListItemId_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."wishList" ALTER COLUMN "WishListItemId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."wishList_WishListItemId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: ads; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.ads ("AdsId", "Description", "ShopId", "StartDate", "EndDate", "IsActive") FROM stdin;
\.


--
-- Data for Name: category; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.category ("CategoryId", "CategoryName") FROM stdin;
1	Other
\.


--
-- Data for Name: location; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.location ("LocationId", "LocationName", "GeoLoacation") FROM stdin;
\.


--
-- Data for Name: notifications; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.notifications ("NotificatoinId", "UserId", "NotificationMessage", "NotificationType", "Seen") FROM stdin;
\.


--
-- Data for Name: products; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.products ("ProductId", "ShopId", "ProductName", "DateInserted", "Brand", "Description", "CategoryId", "Price", "Condition", "ImageUrl", "DeliveryAvailable", "Discount", "ProductCount", "ProductReviewId") FROM stdin;
\.


--
-- Data for Name: reviews; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.reviews ("UserId", "ProductId", "ReviewId", "Rating", "Comment", "ReviewDate") FROM stdin;
\.


--
-- Data for Name: shopFollow; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."shopFollow" ("ShopLikeId", "UserId", "ShopId") FROM stdin;
\.


--
-- Data for Name: shops; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.shops ("ShopId", "ShopName", "BuildingName", "PhoneNumber", "CoverImage", "OwnerId", "CategoryId", "ShopLocationId", "Description", "IsActive") FROM stdin;
\.


--
-- Data for Name: spatial_ref_sys; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.spatial_ref_sys (srid, auth_name, auth_srid, srtext, proj4text) FROM stdin;
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users ("UserId", "Username", "Email", "Password", "Role", "Phone", "DateAccountCreated") FROM stdin;
1	Kidus	se.kidus.yoseph@gmail.com	$2a$11$iIJq.LUUPeCxoG9gNKL6uuUbcXTjeQapIUgSB5k4kXx5iKgGiSt4q	Admin	+251972476097	0001-01-01 00:00:00
\.


--
-- Data for Name: wishList; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."wishList" ("WishListItemId", "ProductId", "UserId", "DateAdded") FROM stdin;
\.


--
-- Name: ads_AdsId_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."ads_AdsId_seq"', 1, false);


--
-- Name: category_CategoryId_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."category_CategoryId_seq"', 2, false);


--
-- Name: location_LocationId_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."location_LocationId_seq"', 1, false);


--
-- Name: notifications_NotificatoinId_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."notifications_NotificatoinId_seq"', 1, false);


--
-- Name: products_ProductId_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."products_ProductId_seq"', 1, false);


--
-- Name: reviews_ReviewId_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."reviews_ReviewId_seq"', 1, false);


--
-- Name: shopFollow_ShopLikeId_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."shopFollow_ShopLikeId_seq"', 1, false);


--
-- Name: shops_ShopId_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."shops_ShopId_seq"', 1, false);


--
-- Name: users_UserId_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."users_UserId_seq"', 2, false);


--
-- Name: wishList_WishListItemId_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."wishList_WishListItemId_seq"', 1, false);


--
-- Name: ads PK_ads; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ads
    ADD CONSTRAINT "PK_ads" PRIMARY KEY ("AdsId");


--
-- Name: category PK_category; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.category
    ADD CONSTRAINT "PK_category" PRIMARY KEY ("CategoryId");


--
-- Name: location PK_location; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.location
    ADD CONSTRAINT "PK_location" PRIMARY KEY ("LocationId");


--
-- Name: notifications PK_notifications; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT "PK_notifications" PRIMARY KEY ("NotificatoinId");


--
-- Name: products PK_products; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT "PK_products" PRIMARY KEY ("ProductId");


--
-- Name: reviews PK_reviews; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT "PK_reviews" PRIMARY KEY ("ProductId", "UserId");


--
-- Name: shopFollow PK_shopFollow; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."shopFollow"
    ADD CONSTRAINT "PK_shopFollow" PRIMARY KEY ("ShopLikeId");


--
-- Name: shops PK_shops; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.shops
    ADD CONSTRAINT "PK_shops" PRIMARY KEY ("ShopId");


--
-- Name: users PK_users; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT "PK_users" PRIMARY KEY ("UserId");


--
-- Name: wishList PK_wishList; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."wishList"
    ADD CONSTRAINT "PK_wishList" PRIMARY KEY ("WishListItemId");


--
-- Name: IX_ads_ShopId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_ads_ShopId" ON public.ads USING btree ("ShopId");


--
-- Name: IX_products_CategoryId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_products_CategoryId" ON public.products USING btree ("CategoryId");


--
-- Name: IX_shops_CategoryId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_shops_CategoryId" ON public.shops USING btree ("CategoryId");


--
-- Name: ads FK_ads_shops_ShopId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ads
    ADD CONSTRAINT "FK_ads_shops_ShopId" FOREIGN KEY ("ShopId") REFERENCES public.shops("ShopId") ON DELETE CASCADE;


--
-- Name: products FK_products_category_CategoryId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT "FK_products_category_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES public.category("CategoryId") ON DELETE CASCADE;


--
-- Name: reviews FK_reviews_products_ProductId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT "FK_reviews_products_ProductId" FOREIGN KEY ("ProductId") REFERENCES public.products("ProductId") ON DELETE CASCADE;


--
-- Name: shops FK_shops_category_CategoryId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.shops
    ADD CONSTRAINT "FK_shops_category_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES public.category("CategoryId") ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

